### ISSUE TITLE
Getting waring message that shows runtime error

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-hubspot#9]
**Describe the bug**
Running any table gives this message
```Warning: failed to start plugin instance 'hub.steampipe.io/plugins/turbot/hubspot@latest': failed to plugin initialise plugin 'steampipe-plugin-hubspot': TableMapFunc 'pluginTableDefinitions' had unhandled error: runtime error: integer divide by zero```

**Steampipe version (`steampipe -v`)**
Example: v0.21.1

**Plugin version (`steampipe plugin list`)**
Example: v0.0.2

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by bigdatasourav** [comment]
@madhushreeray30, The plugin works fine with Steampipe SDK version `v5.6.2`. Could you please try out the same and share your feedback? Looks like an SDK issue.

```
> select * from hubspot_blog_post
+--------------+---------------------------+------------------+----------+-------------+-----------+--------------+->
| id           | slug                      | content_group_id | campaign | category_id | state     | name         | >
+--------------+---------------------------+------------------+----------+-------------+-----------+--------------+->
| 117074562437 | test-my-blog/test-my-blog | 117077029293     | <null>   | 3           | PUBLISHED | test my blog | >
+--------------+---------------------------+------------------+----------+-------------+-----------+--------------+
```
